### ISSUE TITLE
Persisting a seedrandom instance

### ISSUE THREAD

**Issue by pkmnfrk** [davidbau/seedrandom#11]
Hi,

Is it possible to serialize a seedrandom instance, and then restore it later?

My use case is that I'm using it  to procedurally generate levels in a game, and allowing the user to pick the seed. It works great, except that if the user saves and quits, I can't find a way to save and restore the state, so the random numbers will be wrong, as compared to having retained the same instance.

For example, I want this:

```
var rng = seedrandom("Foobar");
console.log(rng()); //0.12345

var state = rng.serialize();

console.log(rng()); //0.23456
console.log(rng()); //0.34567

rng = seedrandom.unserialize(state); // or, seedrandom(state) or whatever

console.log(rng()); //0.23456
console.log(rng()); //0.34567
```

**Comment by carcinocron** [comment]
> So, it needs to be explicitly marked as saveable, or restored from a serialized version that itself must have been marked as saveable. Yeah, that seems like it should work fine.
> 
> Thanks for the quick reply, incidentally! I tried yesterday to look in to implementing this myself, but I now realize that this is a lot more complicated under the hood than something like http://indiegamr.com/generate-repeatable-random-numbers-in-js/ .

thanks for sharing this, being able to store RNG state as a single number is going to be a game changer for me.
