### ISSUE TITLE
Submit to jsDelivr CDN

### ISSUE THREAD

**Issue by kenrick95** [davidbau/seedrandom#18]
I would like to see this library hosted at [jsDelivr](https://github.com/jsdelivr/jsdelivr) CDN. Thanks.

**Comment by davidbau** [comment]
https://github.com/jsdelivr/jsdelivr/pull/4637

**Comment by kenrick95** [comment]
Now it's [available at jsDelivr](http://www.jsdelivr.com/#!seedrandom). Thanks a lot :smile:
