### ISSUE TITLE
New release is not on CDN yet :)

### ISSUE THREAD

**Issue by yoav-zibin** [davidbau/seedrandom#19]
File not found:
cdnjs.cloudflare.com/ajax/libs/seedrandom/2.3.12/seedrandom.min.js

(2.3.11 is fine :))

**Comment by davidbau** [comment]
2.3.12 isn't released yet; master is just bleeding edge.

**Comment by davidbau** [comment]
I've switched the default branch on github to "released" so that people reading the README on github see the last released version.
