### ISSUE TITLE
Additional work on JavaScript randomness

### ISSUE THREAD

**Issue by jeffrose** [davidbau/seedrandom#23]
Have you looked at the work of Johannes Baagøe? Unfortunately his site went down a while ago, but someone made a copy of it on GitHub.

https://github.com/nquinlan/better-random-numbers-for-javascript-mirror

It has some analysis as well as JavaScript PRNG implementations.

**Comment by davidbau** [comment]
Thanks for the pointer.  This is pretty interesting.

**Comment by jeffrose** [comment]
It might be worth it to add Alea (and others) to seedrandom.

**Comment by davidbau** [comment]
The standout was the Alea algorithm, which is impressively simple and fast.
The PR has a direct port of Baagoe's code. It produces the same sequence for the same seeds as Baagoe's original.
