### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by BramVM** [davidbau/seedrandom#28]
Hi, I am using this module to generate a proceduraly generated world in a 3D game project using three.js. I am very glad i found this module since i was breaking my head over seeded randoms.

The only downside i am experiencing is that this doesn't seem to be compatible with browserify.
browserify enables me to use "require();" in browser code. It seems your module provides this functionality to, using require.js?

Anyway when i try to build my project with browserify i get the "can not find module" error.

As soon as i find a solution, i'll post it here.

**Comment by davidbau** [comment]
Thanks.  Let me know what you find. I use seedrandom.js with browserify in another project I work with, and I have not had any issues - however, I'm not an expert in browserify and I am probably missing something.

**Comment by BramVM** [comment]
I'll close this issue for now. Along the way it somehow got fixed and now i can't reproduce the error anymore.
