### ISSUE TITLE
Saved state doesn't work

### ISSUE THREAD

**Issue by Lomacar** [davidbau/seedrandom#33]
I can't even run the example in the documentation:

    var seedrandom = Math.seedrandom;
    var saveable = seedrandom("secret-seed", {state: true});
    for (var j = 0; j < 1e5; ++j) saveable();
    var saved = saveable.state();
    var replica = seedrandom("", {state: saved});
    assert(replica() == saveable());

I get an error: `Uncaught TypeError: saveable.state is not a function(…)`

**Comment by Lomacar** [comment]
@tmedwards None of your examples work. I still always get same error that `XYZ.state is not a function(…)`.

In fact .state is undefined.

**Comment by tmedwards** [comment]
Both of my examples were tested (against the latest release) and do, in fact, work.  I don't know what you're doing wrong.

**Comment by davidbau** [comment]
Although the API is slightly confusing, it does work.  The purpose of the slightly design is to make sure that prng instances are perfectly opaque (e.g., if made available to adversarial code) unless you have explicitly asked for the state to be transparent.

Closing as by-design.
