### ISSUE TITLE
Compatibility with browserify in Node.js

### ISSUE THREAD

**Issue by gaccob** [davidbau/seedrandom#37]
I tried to use seedrandom in Node.js and browerify, but got error like this, (“xxx” means my workspace path)

Error: Cannot find module '../../../../.1.1.4@is-buffer/index.js' from 'xxx/node_modules/.1.0.2@core-util-is/lib'
    at xxx/node_modules/.1.1.7@resolve/lib/async.js:55:21
    at load (xxx/node_modules/.1.1.7@resolve/lib/async.js:69:43)
    at onex (xxx/node_modules/.1.1.7@resolve/lib/async.js:92:31)
    at xxx/node_modules/.1.1.7@resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

So I direct use seedrandom.js file, but got the same error, unless I comment blow lines:
![image](https://cloud.githubusercontent.com/assets/4684354/20215396/e70a4b84-a84e-11e6-9948-de9c1bbe8dc9.png)

Seems `require('crypto')` not Compatibility with browserify?  Anyway, it works now..

OS: Linux VM_47_16_centos 3.10.0-327.el7.x86_64
node: v6.9.1
npm: 3.10.9
browerify: 13.1.1

**Comment by davidbau** [comment]
I've added a simple browserify test to master.  I cannot reproduce your problem; browserify works fine for me.  Feel free to reopen with a specific repro case.
