### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by mreinstein** [davidbau/seedrandom#41]
here's what I get:

```bash
λ git clone git@github.com:mreinstein/seedrandom.git
λ cd seedrandom
λ npm i
λ npm test

> seedrandom@2.4.2 test /Users/michaelreinstein/wwwroot/seedrandom
> grunt travis

Running "uglify:all" (uglify) task
File seedrandom.min.js created: 8.24 kB → 1.62 kB
File lib/alea.min.js created: 3.24 kB → 986 B
File lib/tychei.min.js created: 2.52 kB → 871 B
File lib/xor4096.min.js created: 4.56 kB → 1.15 kB
File lib/xorshift7.min.js created: 2.42 kB → 988 B
File lib/xorwow.min.js created: 1.92 kB → 837 B
File lib/xor128.min.js created: 1.75 kB → 747 B
>> 7 files created.

Running "sed:nullchar" (sed) task

Running "qunit:all" (qunit) task
Testing test/altprng.html 
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.

λ
```

**Comment by davidbau** [comment]
Working on master branch or release?  Let's work off of master, which has slightly better tests+build.

Nevertheless both branches pass for me (xenial, node 7, phantomjs 2.1.7)

**Comment by davidbau** [comment]
The failures I see in travis in your PR have to do with <script src=""> usage; I've left comments in the PR.
https://travis-ci.org/davidbau/seedrandom/jobs/200136001

Closing this issue for now.

**Comment by mreinstein** [comment]
@davidbau you're right, I was in the `release` branch. I didn't realize that was the default. :)

Switching to master makes the tests pass (except for the script issue you mentioned)

sorry for the false alarm!
