### ISSUE TITLE
generating integers within a given range

### ISSUE THREAD

**Issue by nadeemjamali** [davidbau/seedrandom#49]
Is it possible to generate integers within a given range? Say I need numbers between 44 and 315! How can get it?

**Comment by jamuspsi** [comment]
I bet the author has a more efficient method than me, but I use something like this:

```
function randInt(fromval, toval) {
    return Math.floor(fromval + myrng() * (toval - fromval));
}
```

randInt(3,7) -> one of 3, 4, 5, 6

```
function randIntIncl(fromval, toval) {
    return fromval > toval ? \
        Math.floor(toval + myrng() * (fromval - toval + 1)) \
        : Math.floor(fromval + myrng() * (toval - fromval + 1));
}

```
randIntInclusive(3,7) -> one of 3, 4, 5, 6, 7

_(Actually after playing around in jsperf I'm not sure there can be a faster non-native method, so...)_

**Comment by davidbau** [comment]
Thanks for the answer!
