### ISSUE TITLE
Unset seedrandom

### ISSUE THREAD

**Issue by Harrisandwich** [davidbau/seedrandom#53]
Hello,

seedrandom is super awesome, but I have one issue.

How do I unset a global seed of Math.random()? 

For example, say I need Math.random() seeded for a little bit so i use seedrandom('hello', {global: true});

How do I unset it?

Thank you

**Comment by davidbau** [comment]
originalrandom = Math.random
seedrandom('hello', {global: true});
...
Math.random = originalrandom
