### ISSUE TITLE
is it possible to generate a number of 7 digits in length

### ISSUE THREAD

**Issue by dagda1** [davidbau/seedrandom#54]
is it possible to generate a number of 7 digits in length.

I want to use an auto incrementing field in a database to use as the seed each time.

Is it possible to use this library to do this?

**Comment by davidbau** [comment]
Sure, though there are probably better alternatives.

```
// Make a seven-digit number based on i.
seven_digits = parseInt(new Math.seedrandom(i)() * 9e7 + 1e7)
```
