### ISSUE TITLE
Problem with state

### ISSUE THREAD

**Issue by kharandziuk** [davidbau/seedrandom#57]
For some reasons the code bellow returns me an error:
```
  const seedrandom = require('seedrandom');
  const rng = new seedrandom('seed', { saved: true })
  console.log(rng())
  console.log(rng.state())
```

the error:
    ```TypeError: rng.state is not a function```
and my environment:
```
node -v
v10.6.0
```

https://github.com/davidbau/seedrandom/issues/33 – I read that answer and added `new`. It doesn't help

**Comment by davidbau** [comment]
Try changing the second line:

`const rng = new seedrandom('seed', { state: true })`

**Comment by kharandziuk** [comment]
So, stupid)
Thanks! it works!
